build:
  maxIssues: 0

comments:
  active: true
  UndocumentedPublicClass:
    active: true
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true

processors:
  active: false