empty-blocks:
  active: true
  EmptyCatchBlock: #todo with comment
    active: true
    allowedExceptionNameRegex: "^(_|(ignored).*)"
  EmptyClassBlock: #todo class in fun, with comment
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock: # todo with comment
    active: true
  EmptyElseBlock: # todo with comment
    active: true
  EmptyFinallyBlock: # todo with comment
    active: true
  EmptyForBlock: # todo with comment
    active: true
  EmptyFunctionBlock: # todo with comment
    active: true
    ignoreOverriddenFunctions: false
  EmptyIfBlock: # todo with comment
    active: true
  EmptyInitBlock: # todo with comment
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor: # todo with comment
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock: # todo with comment
    active: true
