language: java

jdk:
  - openjdk8

env:
  global:
    - TEST_STATUS=0
    - REPORTS_COLLECTED_STATUS=0
    - TEST_COVERAGE_VERIFICATION_STATUS=0
    - CHECK_README_STATUS=0
    - GH_PAGES_REPORT_STATUS=0

install:
  - true #will prevent Travis from executing `gradle assemble`

before_script:
  - |
    echo "commit: $TRAVIS_COMMIT"
    echo "branch: $TRAVIS_BRANCH"
  - |
    gradle compile || (
      STATUS=$?
      echo "Summary: not compiled!"
      exit $STATUS
    )

script:
  - gradle runTests || TEST_STATUS=$?; $(exit $TEST_STATUS)
  - gradle collectTestReport collectTestCoverageReport || REPORTS_COLLECTED_STATUS=$?; $(exit $REPORTS_COLLECTED_STATUS)
  - gradle checkReadme || CHECK_README_STATUS=$?; $(exit $CHECK_README_STATUS)
  - bash gh-pages-report.sh || GH_PAGES_REPORT_STATUS=$?; $(exit $GH_PAGES_REPORT_STATUS)

after_script:
  - |
    testResultText="passed"; if [ $TEST_STATUS -ne 0 ];then testResultText="failed";fi;
    echo "Summary
      - testing: ${testResultText}
    "