language: java

jdk:
  - openjdk8

install:
  - export BASH_PATH="${TRAVIS_BUILD_DIR}/buildSrc/src/main/resources/travis/bash"
  - source ${BASH_PATH}/set_environment_variables.sh

before_script:
  - source ${BASH_PATH}/before_script.sh

script:
  - gradle runTest || TESTING_STATUS=$?; $(exit $TESTING_STATUS)
  - gradle collectTestingReport collectTestCoverageReport collectDocumentation
  - gradle verifyTestCoverage || VERIFY_TEST_COVERAGE_STATUS=$?; $(exit $VERIFY_TEST_COVERAGE_STATUS)
  - gradle verifyDocumentation || VERIFY_DOCUMENTATION_STATUS=1; $(exit $VERIFY_DOCUMENTATION_STATUS)
  - gradle verifyStyle || VERIFY_STYLE_STATUS=$?; $(exit $VERIFY_STYLE_STATUS)
  - gradle verifyWarning || VERIFY_WARNING_STATUS=$?; $(exit $VERIFY_WARNING_STATUS)
  - gradle verifyReadme || VERIFY_README_STATUS=$?; $(exit $VERIFY_README_STATUS)
  - source ${BASH_PATH}/gh_pages_report.sh || GH_PAGES_REPORT_STATUS=$?; $(exit $GH_PAGES_REPORT_STATUS)

after_failure:
  - BUILD_SUCCESS=1

after_script:
  - bash ${BASH_PATH}/after_script.sh
