language: java

jdk:
  - openjdk8

env:
  global:
    - COMPILE_RESULT=0
    - TEST_RESULT=0

install:
  - true #will prevent Travis from executing `gradle assemble`

script:
  - gradle compile || COMPILE_RESULT=1; exit 1;
  - gradle runTests || TEST_RESULT=1
  - gradle collectTestReport
  - gradle collectTestCoverageReport
  - gradle runTestCoverageVerification
  - gradle checkReadme
  - bash gh-pages-report.sh

after_script:
  - |
    if[$COMPILE_RESULT==0]
    then
      testResultText=if[$TEST_RESULT==0];then "passed";else "failed";fi
      echo "Summary: \n\t- testing: ${testResultText}"
    else
      echo "Summary: \n\t- not compiled!"
    fi