language: java

jdk:
  - openjdk8

env:
  global:
    - TEST_STATUS=0
    - REPORTS_COLLECTION_STATUS=0
    - TEST_COVERAGE_VERIFICATION_STATUS=0
    - CHECK_README_STATUS=0
    - GH_PAGES_REPORT_STATUS=0
    - |
      COMMIT_MESSAGE="commit: [${TRAVIS_COMMIT::7}](https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_COMMIT)"

install:
  - true #will prevent Travis from executing `gradle assemble`

before_script:
  - |
    echo "commit: $TRAVIS_COMMIT"
    echo "branch: $TRAVIS_BRANCH"
  - |
    gradle compile || (
      STATUS=$?
      echo "Summary: not compiled!"
      MESSAGE="${COMMIT_MESSAGE}%0Anot compiled%E2%9D%97%EF%B8%8F"
      bash telegram-send-message.sh $telegram_bot_id $telegram_bot_token $telegram_chat_id $MESSAGE
      exit $STATUS
    )

script:
  - gradle runTests || TEST_STATUS=$?; $(exit $TEST_STATUS)
  - gradle collectTestingReport collectTestCoverageReport || REPORTS_COLLECTION_STATUS=$?; $(exit $REPORTS_COLLECTION_STATUS)
  - gradle checkReadme || CHECK_README_STATUS=$?; $(exit $CHECK_README_STATUS)
  - bash gh-pages-report.sh || GH_PAGES_REPORT_STATUS=$?; $(exit $GH_PAGES_REPORT_STATUS)

after_script:
  - |
    testStatusText="passed"
    if [ $TEST_STATUS -ne 0 ];then testResultText="failed";fi
    reportsCollectionStatusText="collected"
    if [ $REPORTS_COLLECTION_STATUS -ne 0 ];then reportsCollectionStatusText="not collected";fi
    echo -e "Summary
      - testing: ${testStatusText}
      - reports: ${reportsCollectionStatusText}
    "
    MESSAGE="${COMMIT_MESSAGE}%0Acompiled%E2%9C%94%EF%B8%8F"
    echo "tg message: $MESSAGE"
    bash telegram-send-message.sh $telegram_bot_id $telegram_bot_token $telegram_chat_id $MESSAGE