language: java

jdk:
  - openjdk8

install:
  - true #will prevent Travis from executing `gradle assemble`

before_script:
  - |
    echo "commit: $TRAVIS_COMMIT"
    echo "commit message: $TRAVIS_COMMIT_MESSAGE"
    echo "branch: $TRAVIS_BRANCH"

after_script:
  - |
    MESSAGE="$TRAVIS_COMMIT_MESSAGE"
    echo "tg before"
    echo $MESSAGE
    bash telegram-send-message.sh $telegram_bot_id $telegram_bot_token $telegram_chat_id "$MESSAGE"