language: java

jdk:
  - openjdk8

env:
  global:
    - CC_TEST_REPORTER_ID=$code_climate_test_reporter_id

install:
  - true #will prevent Travis from executing `gradle assemble`

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - gradle clean
  - gradle test
  - gradle jacocoTestReport
  - gradle jacocoTestCoverageVerification
  - gradle checkReadme

after_script:
  - JACOCO_SOURCE_PATH="lib/src/main/kotlin lib2/src/main/kotlin" ./cc-test-reporter format-coverage -d -t jacoco ./build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
  - ./cc-test-reporter upload-coverage -d