language: java

jdk:
  - openjdk8

install:
  - export BASH_PATH="${TRAVIS_BUILD_DIR}/buildSrc/src/main/resources/travis/bash"
  - source ${BASH_PATH}/set_environment_variables.sh

before_script:
  - source ${BASH_PATH}/before_script.sh

script:
  - gradle -q runTesting || TESTING_STATUS=$?; $(exit $TESTING_STATUS)
  - gradle -q collectTestingReport collectTestCoverageReport collectDocumentation
  - gradle -q verifyTestCoverage || VERIFY_TEST_COVERAGE_STATUS=$?; $(exit $VERIFY_TEST_COVERAGE_STATUS)
  - gradle -q verifyDocumentation || VERIFY_DOCUMENTATION_STATUS=1; $(exit $VERIFY_DOCUMENTATION_STATUS)
  - gradle -q verifyStyle || VERIFY_STYLE_STATUS=$?; $(exit $VERIFY_STYLE_STATUS)
  - gradle -q verifyWarning || VERIFY_WARNING_STATUS=$?; $(exit $VERIFY_WARNING_STATUS)
  - gradle -q verifyReadme || VERIFY_README_STATUS=$?; $(exit $VERIFY_README_STATUS)
  - bash ${BASH_PATH}/verify_version.sh || VERIFY_VERSION_STATUS=$?; $(exit $VERIFY_VERSION_STATUS)
  - source ${BASH_PATH}/gh_pages_report.sh || GH_PAGES_REPORT_STATUS=$?; $(exit $GH_PAGES_REPORT_STATUS)

after_failure:
  - BUILD_SUCCESS=1

after_success:
  - bash ${BASH_PATH}/after_success.sh

after_script:
  - bash ${BASH_PATH}/after_script.sh
