language: java

jdk:
  - openjdk8

env:
  global:
    - REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
    - REPO_NAME=${TRAVIS_REPO_SLUG#*/}
    - TESTING_STATUS=0
    - TEST_COVERAGE_VERIFICATION_STATUS=0
    - CHECK_README_STATUS=0
    - GH_PAGES_REPORT_STATUS=0
    - TEST_COVERAGE_REPORT_URL=""
    - TESTING_REPORT_URL=""
    - |
      TRAVIS_MESSAGE="Travis [build](https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID) %23$TRAVIS_BUILD_NUMBER"
      REPOSITORY_MESSAGE="Repository: [$REPO_NAME](https://github.com/$TRAVIS_REPO_SLUG) of [$REPO_OWNER](https://github.com/$REPO_OWNER)"
      COMMIT_MESSAGE="commit: [${TRAVIS_COMMIT::7}](https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_COMMIT) \"$TRAVIS_COMMIT_MESSAGE\""
      TELEGRAM_MESSAGE_PREFIX="$TRAVIS_MESSAGE%0A%0A$REPOSITORY_MESSAGE%0A%0A$COMMIT_MESSAGE"

install:
  - true #will prevent Travis from executing `gradle assemble`

before_script:
  - |
    echo "commit: $TRAVIS_COMMIT"
    echo "branch: $TRAVIS_BRANCH"
  - |
    gradle compile || (
      STATUS=$?
      echo "Summary: not compiled!"
      MESSAGE="$TELEGRAM_MESSAGE_PREFIX%0A%0Anot compiled %E2%9D%97%EF%B8%8F"
      bash telegram-send-message.sh $telegram_bot_id $telegram_bot_token $telegram_chat_id "$MESSAGE"
      exit $STATUS
    )

script:
  - gradle runTests || TESTING_STATUS=$?; $(exit $TESTING_STATUS)
  - gradle collectTestingReport
  - gradle collectTestCoverageReport
  - gradle runTestCoverageVerification || TEST_COVERAGE_VERIFICATION_STATUS=$?; $(exit $TEST_COVERAGE_VERIFICATION_STATUS)
  - gradle checkReadme || CHECK_README_STATUS=$?; $(exit $CHECK_README_STATUS)
  - source gh-pages-report.sh || GH_PAGES_REPORT_STATUS=$?; $(exit $GH_PAGES_REPORT_STATUS)

after_script:
  - |
    testingStatusText="passed"
    if [ $TESTING_STATUS -ne 0 ];then testingStatusText="failed";fi
    TESTING_MESSAGE="- testing: ${testingStatusText}"
    if test -z "$TESTING_REPORT_URL" 
    then
      TESTING_MESSAGE+=" / no report provided"
    else
      TESTING_MESSAGE+=" / [report]($TESTING_REPORT_URL)"
    fi
    TEST_COVERAGE_MESSAGE="- test coverage: "
    if test -z "$TEST_COVERAGE_REPORT_URL" 
    then
      TEST_COVERAGE_MESSAGE+=" no report provided"
    else
      TEST_COVERAGE_MESSAGE+=" [report]($TEST_COVERAGE_REPORT_URL)"
    fi
    MESSAGE="$TELEGRAM_MESSAGE_PREFIX%0A%0A$TESTING_MESSAGE%0A$TEST_COVERAGE_MESSAGE"
    bash telegram-send-message.sh $telegram_bot_id $telegram_bot_token $telegram_chat_id "$MESSAGE"