language: java

jdk:
  - openjdk8

env:
  global:
    - TEST_STATUS=0
    - REPORTS_COLLECTED_STATUS=0
    - TEST_COVERAGE_VERIFICATION_STATUS=0
    - CHECK_README_STATUS=0
    - GH_PAGES_REPORT_STATUS=0

install:
  - true #will prevent Travis from executing `gradle assemble`

before_script:
  - gradle compile || echo "Summary - not compiled!";

script:
  - gradle runTests || TEST_STATUS=$?; $(exit $TEST_STATUS)
  - gradle collectTestReport collectTestCoverageReport || REPORTS_COLLECTED_STATUS=$?; $(exit $REPORTS_COLLECTED_STATUS)
  - gradle checkReadme || CHECK_README_STATUS=$?; $(exit $CHECK_README_STATUS)
  - bash gh-pages-report.sh || GH_PAGES_REPORT_STATUS=$?; $(exit $GH_PAGES_REPORT_STATUS)

after_script:
  - |
    testResultText=if[$TEST_STATUS==0];then "passed";else "failed";fi
    echo "Summary
      - testing: ${testResultText}
    "