language: java

jdk:
  - openjdk8

install:
  - true #will prevent Travis from executing `gradle assemble`

script:
  - gradle clean
  - gradle runTests
  - gradle collectTestReport
  - gradle collectTestCoverageReport
  - gradle runTestCoverageVerification
  - gradle checkReadme
  - bash gh-pages-report.sh
