echo "set environment variables..."

newline=$'\n'
REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
REPO_NAME=${TRAVIS_REPO_SLUG#*/}
REPO_OWNER_URL="https://github.com/$REPO_OWNER"
REPO_URL="https://github.com/$TRAVIS_REPO_SLUG"
GIT_HUB_PAGES_URL="https://${REPO_OWNER}.github.io/$REPO_NAME"
TRAVIS_URL="https://travis-ci.com/$TRAVIS_REPO_SLUG"
TESTING_STATUS=0
TEST_COVERAGE_VERIFICATION_STATUS=0
DOCUMENTATION_VERIFICATION_STATUS=0
CHECK_README_STATUS=0
GH_PAGES_REPORT_STATUS=0
TEST_COVERAGE_REPORT_URL=""
TESTING_REPORT_URL=""
DOCUMENTATION_URL=""
TRAVIS_MESSAGE="Travis build [#$TRAVIS_BUILD_NUMBER]($TRAVIS_URL/builds/$TRAVIS_BUILD_ID)"
REPOSITORY_MESSAGE="Repository: [$REPO_NAME]($REPO_URL) of [$REPO_OWNER]($REPO_OWNER_URL)"
COMMIT_MESSAGE="commit: [${TRAVIS_COMMIT::7}]($REPO_URL/commit/$TRAVIS_COMMIT) \"$TRAVIS_COMMIT_MESSAGE\""
TELEGRAM_MESSAGE_PREFIX="$TRAVIS_MESSAGE${newline}${newline}$REPOSITORY_MESSAGE${newline}${newline}$COMMIT_MESSAGE"
